### ISSUE TITLE
Implement a clap or a like/dislike feature

### ISSUE THREAD

**Issue by Rajdeepc** [Rajdeepc/evaluator#2]
1. Create a Like and a Dislike Button on every answer
2.Any users can like or dislike(only logged in users)
3. If a not logged in user clicks on like or dislike, show a modal to let user login, once successful login user can like and dislike

Feel free to open a PR to master branch

**Comment by jasbindar-singh** [comment]
Is the backend ready for this feature? Or is this issue for both backend and frontend?

**Comment by Rajdeepc** [comment]
Both BE and FE needs to be built out.
But you can work on the FE part.
Ill take care of the backend

**Comment by jasbindar-singh** [comment]
Sure, I can start with frontend

**Comment by Rajdeepc** [comment]
@jasbindar-singh  Are you working on the FE part?

**Comment by Rajdeepc** [comment]
Closing this issue since it is implemented
